# This is a TOML comment

# This is a multiline
# TOML comment
n = 23
m = 25
f = "noooo"
k = 1.26shajsa

python = 3
apertium = 3.0
lttoolbox = 3.3
apertium-lex-tools = 0.1


="ajadkjada"
hbahsbjnadskklamlald
git = 2.2